#!/bin/bash
OUTFILE="package-graph.gv"
cat > $OUTFILE <<EOF
digraph packagedeps {
rankdir="LR"
node [fontsize=10, shape=box, height=0.25]
edge [fontsize=10]
EOF

for file in requires/* ; do name=$(basename $file) ; cat $file  | awk '{print $1}' | xargs -l1 -I+ echo "\"+\" -> \"$name\"" ; done  >> $OUTFILE
echo "}" >> $OUTFILE
